# 특성공학 


In [32]:
import numpy as np
import pandas as pd 

df = pd.read_csv('./perch.csv')
perch_data = df.to_numpy()

perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])
#두꼐 길이 높이 를 고려해서 무게를 예측하는 모델을 만드려고한다. 


In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(perch_data, perch_weight, random_state=42)

In [34]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
print(lr.coef_, lr.intercept_)
print(lr.score(X_train, y_train))
print(lr.score(X_test, y_test))

[ 9.07538153 69.46401443 38.00385678] -599.1708082981093
0.9559326821885706
0.8796419177546368


In [28]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False)
poly.fit([[2, 3, 5]])
poly.transform([[2, 3, 5]])


array([[ 2.,  3.,  5.,  4.,  6., 10.,  9., 15., 25.]])

In [29]:
poly = PolynomialFeatures(include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

X_train_poly.shape, poly.get_feature_names_out()

((42, 9),
 array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
        'x2^2'], dtype=object))

In [30]:
lr_p = LinearRegression()
lr.fit(X_train_poly, y_train)

print(lr.score(X_train_poly, y_train))
print(lr.score(X_test_poly, y_test))

lr.coef_, lr.intercept_



0.9903183436982124
0.9714559911594159


(array([  34.80604039,  -88.68430232, -184.11606694,   -2.2696004 ,
           8.74890226,    9.41670602,   27.76120631, -119.89306061,
          93.68198334]),
 np.float64(124.06521772233401))

In [31]:
poly = PolynomialFeatures(degree=5, include_bias=False)
X_train_p5 = poly.fit_transform(X_train)
X_test_p5 = poly.fit_transform(X_test)
X_train_p5.shape
# 초 과대 적합(Overfitting) -> 훈련셋에는 완벽한데, 테스트는 망한
lr.fit(X_train_p5, y_train)
lr.score(X_train_p5, y_train)
lr.score(X_test_p5, y_test)

-144.4051193329733

# 규제 (regularization)
- 과대적합(Overfitting) 방지 
- 릿지(ridge) 회귀: 계수를 제곱한 기준으로 규제 
- 라쏘(lasso)회귀 : 절댓값 기준으로 규제 

In [37]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
#훈련셋으로 스케일링 학습 
ss.fit(X_train_p5)
#훈련 & xptmxm ahen gnsfustpt rlwnsdmfh tmzpdlffld wlsgod 
X_train_scaled = ss.fit_transform(X_train_p5)
X_test_scaled = ss .fit_transform(X_test_p5)

X_train_p5

array([[1.96000000e+01, 5.14000000e+00, 3.04000000e+00, ...,
        7.42244501e+02, 4.38992857e+02, 2.59637799e+02],
       [2.20000000e+01, 5.88000000e+00, 3.52000000e+00, ...,
        1.50793507e+03, 9.02709432e+02, 5.40397483e+02],
       [1.87000000e+01, 5.20000000e+00, 3.12000000e+00, ...,
        8.21240709e+02, 4.92744425e+02, 2.95646655e+02],
       ...,
       [2.56000000e+01, 6.56000000e+00, 4.24000000e+00, ...,
        3.28023719e+03, 2.12015331e+03, 1.37034299e+03],
       [4.20000000e+01, 1.28000000e+01, 6.87000000e+00, ...,
        5.31239245e+04, 2.85126063e+04, 1.53032504e+04],
       [3.45000000e+01, 1.02600000e+01, 6.39000000e+00, ...,
        2.74661189e+04, 1.71060916e+04, 1.06537939e+04]], shape=(42, 55))

In [39]:
from sklearn.linear_model import Ridge 
ridge = Ridge(alpha=10)
ridge.fit(X_train_scaled, y_train)
print(ridge .score (X_train_scaled, y_train))
print(ridge.score(X_test_scaled, y_test))


0.988728468997471
0.9103745241423852


In [40]:
import matplotlib.pyplot as plt 
train_score = []
test_scoer = []

alpha_list = [0.001, 0.01,  0.1, 1, 10, 100 ]

for alpha in alpha_list:
    ridge= Ridge(alpha=alpha)
    ridge.fit(X_train_scaled, y_train)
    s1 = ridge .score (X_train_scaled, y_train)
    s2 = ridge.score(X_test_scaled, y_test)
    train_score.append(s1)
    train_score.append(s2)

plt.plot

<function matplotlib.pyplot.plot(*args: 'float | ArrayLike | str', scalex: 'bool' = True, scaley: 'bool' = True, data=None, **kwargs) -> 'list[Line2D]'>

In [ ]:
#alpha = 0.1

alpha in alpha_list:
ridge= Ridge(alpha=alpha)
ridge.fit(X_train_scaled, y_train)
s1 = ridge .score (X_train_scaled, y_train)
s2 = ridge.score(X_test_scaled, y_test)

In [ ]:
from sklearn.linear_model import Lasso 

train_score = []
test_scoer = []

alpha_list = [0.001, 0.01,  0.1, 1, 10, 100 ]

for alpha in alpha_list:
    ridge= Lasso(alpha=alpha)
    ridge.fit(X_train_scaled, y_train)
    s1 = ridge .score (X_train_scaled, y_train)
    s2 = ridge.score(X_test_scaled, y_test)
    train_score.append(s1)
    train_score.append(s2)



In [ ]:
lasso = Lasso (alpha=10)
lasso.fit(X_train_scaled, y_train)

