    - 데이터 분석:**문제를 정의하고 인사이트 도출**(고객구매패턴  분석+ 의사결정)
    - 머신러닝: 데이터를 학습하여 **예측** (분류, 추천 )
-데이터 분석: 데이터를 분석하여 의사결정에 도움을 준다.
    - 의사결정 데이터 기반의 근거

    - 패턴 발견, 예측(머신러닝) 

    모델링 == 함수
- DA Flow(흐름)
    1. 문제정의
    2. 데이터수집
    3. 데이터 정제(결측, 이상치 처리)
    4. 데이터탐색 - 시각화 (평균, 분포 , 상관관계, 막대그래프, 히스토그램)
    5. 통계 분석 및 해석 (수학 -> 가설 검정, 회귀 분석)
    6. 결론도출 
- 시트 vs DB vs python
    - 시트는 편함. -밀키트
    - DB는 대용량 CRUD **저장** (억단위)- 업소용 냉장고 
    - 파이썬 시각화, 분석, 머신러닝 - 요리 
- 라이브러리 
    - 'Numpy': 빠름(수학, 통계, 배열연산이 빠르다.)(파이썬 리스트 vs Numpy 배열 차이점)
    - 'pandas': 표(DataFrame) -> 'numpy' 기반으로 만들어짐 
    - 'matplotlib; : 시각화(그래프)
    - 'seaborn' : 시각화 심화 
    - 'scipy' : 고급통계, 수학연산
    - 'sckitlearn'; 머신러닝 
- 배열과 리스트는 다른개념 리스트가 더 편하고 유연, 느리고 보장되지도 않는다. 배열은 불편하고 고정되지만 빠르고 보장된다
 -  % pip install numpy 이렇게 해도 프로그램 설치 가능 


- 파이썬 리스트와 Numpy 배열의 차이점 
numpy 배열은 동일한 자료형만 저장한다. 그리고 벡터화 연산 및 C 기반 구현으로 빠르다. 또한 배열끼리 덧셈/ 곱셈 등 연산이 가능핟. 
리스트는 내장함수 한정한 기능을 가지고 있다. 범용 프로그래밍에 적합하다. 

In [ ]:
python_list =[1, 2, 3, 4, 5]
result = [x*2 for x in python_list]
print(result)


arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))
print('차원', arr.ndim)
print('형태', arr.shape)
print('크기', arr.size)



In [ ]:
import numpy as np
array = np. array([1, 2, 3, 4, 5])
result = array * 2
print(result)

In [ ]:
l2d = [
    [1, 2, 3],
    [4, 5, 6]
]
arr2d = np.array(l2d) #l2d의 배열을 나타낸다는 뜻 

arr2d.shape, arr2d.ndim, arr2d.size, arr2d.dtype


In [ ]:
#실수형 arr
np.array([1, 2, 3], dtypr=float)

arr2d.dtype

In [ ]:
z1d = np.zeros(5)
z2d = np.zeros((2,3))
print(z1d, z2d)
print()
#1로 채워짐
o1d =np.ones(5)
o2d = np.ones((2,3))
#7로 채움 
n1d = np.full (5,7)
n2d = np. full((2,3),7)
print(n2d)
#빈칸이지만 먼저 만듦
empty = np.empty(3)
print (empty)

In [ ]:
#시퀀스 데이터 # 정렬 방식 변수명 = np.지정어(배열) 
range_arr =np.arange(0, 10, 2)
print(range_arr)
#등간격 실수 베얄 
lin_space = np.linspace(1,2,5)
print (lin_space)
#로그 스케일 
log_space = np.logspace(0, 2 ,5) #10^0~10^2 5개 요소 
print(log_space)

In [ ]:
#난수 배열 

#균등분포 난수(0~1)사이를 균등확률 분포 
random = np.random.rand(3,3) #0부터 1사이의 실수 
print(random)

# 정규 분포 난수 
normal =np.random.randn(3,3)
print(normal)

#정수만 난수
int_random = np.random.randint(0, 10, (3,3))

#시드설정(랜덤재현가능) 
np.random.seed(42)#랜덤상황 42 고정 위ㄱ의 결과도 모두 변경됨 
np.random.rand(3) #시뮬레이팅 할때 사용 


### np.random.rand(3,3)
[0,1) 사이의 균등 분포 이다 
- 모든 수가 동일한 확률로 나온다.  
- 표준 정규 분포는 평균이 0이고 표준편차가 1인 정규분포다. 0근처 값이 자주나옴

	•	랜덤한 확률/비율 → rand()
	•	통계적/자연현상 모델링 → randn() (정규분포)


In [ ]:
# 배열의 데이터타입 
# 데이터 타입 확인
arr = np.array([1, 2, 3])
print(arr.dtype)

#데이터 타입 지정 생성
f_arr =np.array([1, 2, 3], dtype = np.float64)
print(f_arr.dtype)

#데이터 타입 변경 
converted = arr.astype(np.float64) 
print(converted.dtype)

#문자열 숫자로 변경하기
str_arr = np.array(['1.2', '2.3', '3.4']) 
num_arr = str_arr.astype(float) #np.floatXX ㅏㄹ고 지정안하고 float 쓰면 64
print(num_arr, num_arr.dtype)

In [ ]:
#메모리 사용량
print(arr.itemsize) # 8byte 한칸에 8바이트를 차지한다. 정수 
print(converted.itemsize) #float32 -> 4byte
#총 메모리 사용량 
print (arr.nbytes)#8byte *3칸 
print(converted.nbytes)


In [ ]:
# 배열 재구성 하기 
arr = np.arange(12)
print(arr)
reshaped = arr.reshape(3, 4)
print(reshaped)

reshaped3d = arr.reshape(2, 2, 3) #2 page, 2row * 3col
print(reshaped3d)

#자동계산 
auto1 = arr.reshape(3,-1) #row 3개 열알아서 
auto2 = arr.reshape(-1, 6)#row 알아서 col 6개 

print(auto1)
print(auto2)


In [ ]:


# reshape -> 원본 그대로, 새로운 배열 만드
# resize  -> 원본을 바꿈

arr = np.arange(12)
reshaped = arr.reshape(3, 4)  # 새로운 배열 리턴
print(reshaped)
print(arr)

arr.resize(3, 4)  # arr 이 바뀜
print(arr)



In [ ]:
#N차원 -> 1차원
arr = np.array([[1, 2, 3], [4,  5, 6]])
r = arr.ravel() #뷰(원본 연결) -> 빨리 펼쳐 보기 
f = arr. flatten()# 복사본 -> 안전하게 새로 만들어서 활용 
r[0]= 100
f[0] = -100
print(arr)
print(r, f)


In [ ]:
#전치  -> 행과 열을 교환 
arr_2d = np.array([[1,2, 3],[4, 5, 6]])
print(arr_2d)
arr_2d.transpose(), arr_2d.T

In [ ]:
#1~15 정수 배열 
print(np.arange(1, 16))
#np.array(range(1,16))
#0~9까지 홀수 
print(np.arange(1,10,2))

#0~1까지 균등 6등분 (5구간) 배열
print(np.linspace(0, 3, 6))



In [ ]:
# 4*4 단위행렬 (identity matrix) 대각선 1 나머지 0
print(np.eye(3))
#3 * 4 사이즈의 1로 가득찬 int 배
np.ones((3, 4),dtype=int)

# 2 * 3 * 4사이즈 0~1 난수 배열 
np.random.random((2, 3, 4)) #튜플로 차원 지정 --> 오래된 버전에서 주로 씀 
np.random.rand(2, 3, 4)#rand와 random 의 차이: size 지정 인자로 차원 지정 -> 최신버전에서 주로씀 

## 배열의 인덱싱/ 슬라이싱


In [ ]:
#넘파이의 인덱싱파트 
arr = np.array([ 10, 20, 30, 40, 50])

print(arr)
arr[0]
arr.half
#배열은 사이즈를 늘리거나 줄이는 것이 불가능하여 새로만들어야한다.

In [ ]:
arr_2d = np.array(range(1, 10)).reshape(3,3)
arr_2d

arr_2d[0, 0] #numpy 에서만 지원 arr_2d[0][0]
arr_2d[1, 1]

arr_2d[1] # 행 접근 
#변경 
arr_2d[0,0] =100
arr_2d


In [ ]:
#슬라이싱 
arr = np.arange(10)
print(
    arr[2:5],
    arr[:5],
    arr[5:]
)
print(
    arr[1:8:2],
    arr[::2]
)
print(
    arr[::-1],
    arr[7:2:-1]
)
#슬라이싱으로 일괄 변경 파이썬에선 없음.
arr[3:6] = 100
print(arr)

In [ ]:
#다차원슬라이싱

array_2d =np.arange(1,13).reshape(3, -1)##
array_2d 

#row(행 )슬라이싱 ->  idx1 0,1행
print(arr_2d[0:2])

#열 슬라이싱 
print(arr_2d[:, 1:3])##->모든 행의 idx1, 2 열을 가져온 것 
# 1,2 행/0,1 열 
print(arr_2d[1:3, 0:2])
#간격지정 -> 행 열모두 2간격 
print(arr_2d[::2, ::2])

In [ ]:
#다차원 배열 슬라이싱으로 변경 
#부분배열 일괄변경 
arr_2d[0:2, 0:2] =0
print(arr_2d)

# 열 교체(모든행, idx 3열) ->벡터->교체->원 본의 열이 바뀜
arr_2d[:, 3] = [100, 200, 300] #슬라이싱을 했는데 원본과 연결되어 교체가 가능한 것이 신기하다 열교체!! 

In [ ]:
#boolean인덱싱( 조건에 따라 배열 요소 선택 -필터링)/44

arr = np.arange(1,6)
arr
#마스킹 (T/F)로 바꿈 
mask = arr > 3
print(mask,arr)

# 마스킹 배열로 필터링 
print(arr[mask])

#직접 조건 
print (arr[arr>3])

# 다중 조건 
print(arr [ (arr>2) & (arr<5)]) #and
print(arr [ (arr==1) | (arr>3)]) #OR 연산 

In [ ]:
# 2 차원 배열 불리언 인덱싱 
arr_2d = np.arange(1, 10).reshape(3 ,3)

mask = arr_2d > 5 
print(arr_2d[])
print(arr_2d[arr_2d > 5 ]) #원본 매트릴스 형태 없음 True 로 필터링 된 애들만 벡터로 나오고 있음 

#조건에 맞는 행만 선택
arr_2d [:, 0:3:2] #모든 행에 대해서 0이랑 2에 해당하는 열만 선택 
row_mask = np.array([True, False, True])
print(arr_2d[row_mask]) #row T, F, T -> 0, 2 row 만 뽑음 ###### 이해안됨


In [ ]:
#Fancy 인덱싱 
arr = np.arange(10 , 60, 10)
arr[1]
print(arr)
# arr[1, 2] -> arr[1][2]
print(arr[[1, 2]]) #arr[1], arr[2]를 뽑아라
print(arr[[0, 2, 3]])

print(arr[[0,0,1,1,2]]) 
print(arr[[4, 3, 4, 1, 0]])
 # 각 인덱스를 다가져옴   ##이해 잘 안됨 ㅜㅜㅠㅠㅠㅠㅠ



In [ ]:
arr_2d = np.arange(1, 10).reshape(3 ,3)
print(arr_2d)

arr_2d [0]#
#특정 행만 선택 
print(arr_2d[ [0]]) # row 0,2  구냥 0이랑 2 갖고와
print()
#행과 열 동시에 선택 
print(
    arr_2d[ #(0,0), (1, 2),(2,1) 순서로 벡터 만듦 
        [0, 1, 2],
        [0, 2, 1]
    ]
)

#행렬의 특정 열을 순서 바꾸기 
print(
    arr_2d[
        :, # 모든 행 
        [2,0,1] #열 idx 를 이렇게 바꿔라
    ]
)

In [ ]:
# 10부터 20까지의 정수 배열 생성
arr = np.arange(10, 21)
print('원본', arr)
# 문제1: 배열의 첫 번째, 세 번째, 마지막 요소 출력
print (arr[0], arr[2], arr[-1])
# 문제2: 인덱스 2부터 5까지 요소 출력
print(arr[1:6])
# 문제3: 처음부터 5번째 요소까지 모든 짝수 인덱스 요소 출력
print(arr[0:5])
# 문제4: 배열의 요소를 역순으로 출력
print(arr[::-1])

In [ ]:
# 3 * 4 matrix
matrix = np.arange(12).reshape(3, 4)
print( matrix)

# 문제1: (1,2) 위치의 요소 출력
print(matrix[1,2])

# 문제2: 두 번째 행 전체 출력
print(matrix[1])

# 문제3: 마지막 열 전체 출력
print(matrix[-1])
# 문제4: 첫 번째와 세 번째 행의 두 번째와 네 번째 열 요소만 추출
print(matrix[[0,2,:],[1,3, :]])

print matrix[
    
     [(0,2),:],[:,(1,3)]
matrix[np.ix_]
    
]

In [ ]:
arr = np.arange(1, 21)
print('원본', arr)

# 문제1: 5의 배수만 선택하여 출력

# 문제2: 3보다 크고 15보다 작은 요소 선택

# 문제3: 7의 배수이거나 홀수인 요소 선택
matrix = np.arange(1, 21).reshape(5, 4)
print('원본', matrix)

# 문제4: 10보다 큰 요소만 100으로 변경(슬라이싱/불리언 인데싱 -> 뷰생성 )원본데이터 연결))
matrix

In [ ]:
## 선형대수 연산 
a = np.array([1, 2, 3,4 ])
b = np.array([5, 6, 7, 8])

print(a+b)
print(a-b)
print(a*b )
print(a/b)
print(a**2)
print(a**b)


In [ ]:
a = np.array([True, False, True, False ])
b = np.array([False, True, True, False])

#논리연산 
#AND
print(a&b)
#OR
print(a|b)
print(~a) #실제와 반대로 적으라는 의미


## 배열<-> 스칼라(단일값) 연산
>Broadcastinf(스칼라가 배열 크기에 맞게 확장)

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a ** 2)
print(a ** b)

a = np.array([True, False, True, False])
b = np.array([False, True, True, False])

# 논리연산
# AND
print(a & b)
# OR
print(a | b)
# NOT
print(~a)

# 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 스칼라 덧셈
print(arr + 10)     # [11 12 13 14 15]

# 스칼라 뺄셈
print(arr - 1)      # [0 1 2 3 4]

# 스칼라 곱셈
print(arr * 2)      # [2 4 6 8 10]

# 스칼라 나눗셈
print(arr / 2)      # [0.5 1.  1.5 2.  2.5]

# 스칼라 거듭제곱
print(arr ** 2)     # [ 1  4  9 16 25]
# 스칼라 비교(불리언 배열)
print(arr > 3)      # [False False False  True  True]
print(arr == 2)     # [False  True False False False]











### 매트릭스(2d)<->스칼라(단일값)연산 

In [ ]:
# 2차원 배열
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 스칼라 연산
print(arr_2d + 10)
# [[11 12 13]
#  [14 15 16]]

print(arr_2d * 3)
# [[ 3  6  9]
#  [12 15 18]]

## 매트릭스(행렬) <-> 벡터 (1줄) 연산 

In [ ]:

matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

# 행렬 + 행 벡터
print(matrix + vector)

# 열 벡터 브로드캐스팅
col_vec = np.array(
    [
        [100], #열을 의미하고 있음 매트릭스아니고 열을 나타내기 위한 벡터임 
        [200]
    ]
)
print(matrix + col_vec)



In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])
print('Matrix shape', matrix.shape)
print('Matrix shape', vector.shape)
#1. vextor(3,)가 앞에 1이 추가됨 --> Matrix (1,3)으로 변함.  
#2. 더해야하는 matrix(2,3)이랑 줄수가 같을 때 까지 row 복사함 
print('Matrix + Vectoer')
print(matrix + vector)


In [ ]:
# 브로드 캐스팅 가능한 경우 

A = np.ones((3, 2))       # 3x2 배열
B = np.ones((2,))         # 길이 2인 1차원 배열 (1x2로 해석) (행벡터)
C = np.ones((3, 1))       # 3x1 배열 (사실상 열벡터)

print("A + B 형태:", (A + B).shape)  # (3, 2) - B는 각 행에 브로드캐스팅
print(A + B)


print("A + C 형태:", (A + C).shape)  # (3, 2) - C는 각 열에 브로드캐스팅
print(A + C)

In [ ]:
matrix = np.arange(1, 21).reshape(5, 4)
print('원본', matrix)



In [ ]:
#연산 중 데이터 자동 변환
int_arr =np.array([1, 2, 3])
float_arr = np.array([1.5, 2.5, 3.5])

#int + float =flaot
print(int_arr + float_arr)
#int/int= float 
print(int_arr/2)
print(int_arr //2)

In [ ]:
arr1 = np.array([8, 12, 6, 10])
arr2 = np.array ([3, 4, 1, 20])

print(arr1 ** 2)
print(arr1 ** 0.5, np.sqrt(arr1)) # 같은 결과 
#각 자리마다 최대값만 모음
print(np.maximum(arr1,arr2))
# aee1+arr2 의 모든 자리수를 더한 총합 
print(np.sum(arr1 + arr2))

In [ ]:
# 테스트 배열
x = np.array([0, np.pi/4, np.pi/2, np.pi])
y = np.array([1, 2, 3, 4])

# 삼각함수
print("sin(x) =", np.sin(x))  # [0., 0.70710678, 1., 0.]
print("cos(x) =", np.cos(x))  # [1., 0.70710678, 0., -1.]
print("tan(x) =", np.tan(x))  # [0., 1., 16331239353195370., 0.]

# 역삼각함수
print("arcsin(sin(x)) =", np.arcsin(np.sin(x)))

# 지수와 로그
#자연상수 e^1, e^2,e^3
print("exp(y) =", np.exp(y))  # [2.71828183, 7.3890561, 20.08553692, 54.59815003]
#자연 상수 log e 
print("log(y) =", np.log(y))  # [0., 0.69314718, 1.09861229, 1.38629436]
print("log10(y) =", np.log10(y))  # [0., 0.30103, 0.47712125, 0.60205999]
print("log2(y) =", np.log2(y))  # [0., 1., 1.58496250, 2.]

# 제곱근과 거듭제곱
print("sqrt(y) =", np.sqrt(y))  # [1., 1.41421356, 1.73205081, 2.]
print("power(y, 2) =", np.power(y, 2))  # [1, 4, 9, 16]

# 절대값과 부호
z = np.array([-2, -1, 0, 1, 2])
print("abs(z) =", np.abs(z))  # [2 1 0 1 2]
print("sign(z) =", np.sign(z))  # [-1 -1  0  1  1]

# 소수점 처리
w = np.array([1.2, 2.7, 3.5, 4.9])
print("floor(w) =", np.floor(w))  # [1. 2. 3. 4.] (내림)
print("ceil(w) =", np.ceil(w))   # [2. 3. 4. 5.] (올림)
print("round(w) =", np.round(w))  # [1. 3. 4. 5.] (반올림)
print("trunc(w) =", np.trunc(w))  # [1. 2. 3. 4.] (소수점 버림)


##포아송 분포 공부 (통계학)



In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 기본 집계
print("합계:", np.sum(arr))          # 45
print("평균:", np.mean(arr))         # 5.0
print("최소값:", np.min(arr))        # 1
print("최대값:", np.max(arr))        # 9
print("표준편차:", np.std(arr))      # 2.581988897471611
print("분산:", np.var(arr))          # 6.666666666666667

In [ ]:
 
# 축을 따라 집계
print("행별 합계:", np.sum(arr, axis=1))  # [ 6 15 24]
print("열별 합계:", np.sum(arr, axis=0))  # [12 15 18]
print("행별 평균:", np.mean(arr, axis=1))  # [2. 5. 8.]
print("열별 평균:", np.mean(arr, axis=0))  # [4. 5. 6.]
print("행별 최소값:", np.min(arr, axis=1))  # [1 4 7]
print("열별 최소값:", np.min(arr, axis=0))  # [1 2 3]


In [ ]:
# 누적 합계 (cumulative sum)
print("누적 합계:", np.cumsum(arr))  # [ 1  3  6 10 15 21 28 36 45]
print("행별 누적 합계:")
print(np.cumsum(arr, axis=1))
# [[ 1  3  6]
#  [ 4  9 15]
#  [ 7 15 24]]

# 누적 곱 (cumulative product)
print("누적 곱:", np.cumprod(arr))  # [1 2 6 24 120 720 5040 40320 362880]

# 중앙값 (median)
print("중앙값:", np.median(arr))        # 5.0
print("행별 중앙값:", np.median(arr, axis=1))  # [2. 5. 8.]
print("열별 중앙값:", np.median(arr, axis=0))  # [4. 5. 6.]

# 백분위수 (percentile)
print("25% 백분위수:", np.percentile(arr, 25))  # 3.0
print("50% 백분위수:", np.percentile(arr, 50))  # 5.0 (중앙값과 동일)
print("75% 백분위수:", np.percentile(arr, 75))  # 7.0

# 가중 평균 (weighted average)
weights = np.array([0.1, 0.3, 0.6])  # 가중치
data = np.array([2, 5, 8])
print("가중 평균:", np.average(data, weights=weights))  # 6.5


In [ ]:
# 샘플 배열
arr = np.arange(12)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 균등 분할
print("3개로 균등 분할:")
print(np.split(arr, 3))  # [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 위치 지정 분할
print("위치 지정 분할 (인덱스 3, 8 기준):")
print(np.split(arr, [3, 8]))  # [array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 2차원 배열 분할
arr_2d = np.arange(16).reshape(4, 4)
print("2차원 배열:")
print(arr_2d)

# 행 방향 분할
print("행 방향 분할:")
print(np.split(arr_2d, 2, axis=0))  # 2개 배열로 (각 2x4)
print(np.vsplit(arr_2d, 2))  # 동일한 결과

# 열 방향 분할
print("열 방향 분할:")
print(np.split(arr_2d, 2, axis=1))  # 2개 배열로 (각 4x2)
print(np.hsplit(arr_2d, 2))  # 동일한 결과

In [ ]:
import numpy as np

In [ ]:
#1차원 배열 결합 
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concat((arr1,arr2)) #각자 따로 넣으면 에러나서 튜플이나 리스트로 묶어서 넣어야한다. 
print (result)

In [ ]:
#2차원 배열 결합 
arr2d1 =np. array([[1,2],[3,4]])
arr2d2 =np. array([[5,6],[7,8]])
result2 = np.concat((arr2d1, arr2d2),axis =0)
print(resuilt)
result 
resslut4= np.concat 

result3 = np.concat((arr2d1m arr2d2))
result4 dstack _> 겹쳐서 텐서로 만든다 
매트릭스두개를 겹쳐서 텐서로 만든다  ##다시피기 





resilt4 - np.oncat((arr2f2arr2f2,acs= 2 ))

In [ ]:
#벡터를 차원확장 (행이냐 열이냐)
arr = np.array([1, 2, 3, 4])
print(arr)

#row vector -> [[1,2,3,4]]
row_vector = np.expend_dims(arr, axis=0)
print(row_vector)
row_vector2 = arr[np.newaxis, :]
print(row_vector2)

#col vector -> [[1],[2],[3],[4]]
col_vector = np.expend_dims(arr, axis = 1)
print(col_vector)


In [ ]:
# 차원 축소 
arr = np.array([ [ [1], [2], [3] ]])
print(arr, arr.shape)

# 모든 단일차원(shape에서 1나온 것들 제거)
print(np.squeeze(arr)) #[1,2,3]

#특정 축만 제거
arr2 =np.array([[[1, 2, 3]]])
print(arr2, arr2.shape) #1 1 3
print(np.squeeze(arr2, axis=1)) #1 3 

# axis 
0은 행방향 1은 열방향 상하:0 좌우:1 

In [ ]:
## 자습 문제 
# 학급별 시험 점수 (5개 학급, 각 10명의 학생)
scores = np.random.randint(50, 101, size=(5, 10))  # 50~100 사이 점수
print("학급별 점수:")
print(scores)

# 문제1: 전체 평균과 표준편차
average = np. mean(scores)
std_dev = np.std(scores)
print(average)
print(std_dev) 

# 문제2: 학급별 최고점과 최저점
max1 = np.max(scores)
min1 = np.min(scores)
print(max1)
print(min1)

# 문제3: 전체 학생 중 상위 25%와 하위 25% 컷오프 점수

#1차원으로 변환 (전체 학셍 점수)
flat_scores = scores.flatten()
lower_cutoff = np.percentile(flat_scores, 25)
upper_cutoff = np.percentile(flat_scores, 75)
print(lower_cutoff,upper_cutoff)

# 문제4: 학급별 평균이 가장 높은/낮은 학급 찾기 
#1. 학급별 평균 계산 (행별 평균)
class_means = np.mean(scores, axis =1)
print(class_means)
#2. 평균이 가장 높은 학급 
highest_idx  ##내일 다시 풀어보기 


In [ ]:
#

## 복습주제
1. numpy와 list의 차이 
    - numpy: 빠르지만 값이 고정되어있음.연산이 가능함.
    - list : 내장함수 계산만 가능함. 
2.  

## 유틸리티 함수


# where

In [ ]:
# where 
arr =np.arange(10)\
#단순 필터링 (짝수)
print(np.where(arr % 2 == 0)) 
#값을 바꿀 수 있다
print(np.where(arr % 2== 0, '짝수', '홀수'))

arr2d = np.random.randint(0,10,(3,3))
print(arr2d)
print(np.where)

# 5보다 큰 값들은 *2 아니면 그대로 
np.where(arr2d > 5, arr2d *2 , arr2d)

arr2d [arr2d > 5]


In [ ]:
#argmax, argmin
#벡터에서 최대/최소 위치 
arr = np.array([3, 5, 1, 0, 4])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)

print(max_idx,min_idx)

#매트릭스에서 최대/최소 
np.random.seed(23)
arr2d = np.random.randint(0,10,(3,3))
print(arr2d) 

#각 열에서 최소값의 idx
col_min= np.argmax(arr2d, axis = 1)
print(col_min)

In [ ]:
# unoque 고유값 찾기 
arr = np.array([1,2,3,4,5,4,5,1,4,2,6,4])
unique_values = np. unique(arr)
print(unique_values)
values,count np.unique(arr,return_coints =True)
print(valus)
print(count)

#값들 개수->dict
freq_dict = dict(zip(values,count))
print(freq_dict)



In [ ]:
#r가장 많이 등장하는 숫자 찾기
np.argmax(count)
idx = np,argmax(count)
print()

In [ ]:
#sort, argsort 
arr =np.array([3,5,1,0,4,2,7])
#오름차순 정렬 ASC
print(np.sort(arr))
#내림차수ㄴ정렬 DESC
print(np.sort)



In [ ]:
# 가상의 학생 시험 점수 데이터
math_scores = np.array([85, 90, 75, 95, 70, 80, 65, 75, 90, 85])
science_scores = np.array([90, 85, 80, 95, 70, 75, 65, 80, 85, 90])
english_scores = np.array([80, 85, 90, 80, 75, 90, 70, 75, 85, 95])

subjects = ['수학', '과학', '영어']
scores = np.vstack((math_scores, science_scores, english_scores))

In [ ]:
# 기본 통계 (과목별 평균, 중앙값, *표준편차*, 최소, 최대)
arr1 = np.mean(scores, axis = 0)
arr2 = np.median(scores,axis=0)
arr3 = np.std(scores, axis = 0)
arr4 = np.min(scores, axis =0)
arr5 = np.max(scores, axis=0)

- 총점 기준 상위 3명 학생의 정보  
    1. scores에 존재하는 각 값들을 열별로 (axis =1) 합해서 총합을 구한다. 
    2. 총합변수를 만들고 총합을 내림차순으로 정렬한다.()
    3. 총합에서 0~2까지의 인덱스만 출력한다.  
-  | 학생번호(idx) | 수학 | 과학 | 영어 | 총점 |
     1. argmax 를 활용해서 학생인덱스만 출력하고 '학생번호' 변수에 저장한다. 
     2. subject를 | 로 나누어 나타내고 



In [ ]:
## 총점 기준 상위 3명 학생의 정보 
totals = np.sum(scores, axis = 0)
top3_idx = np.sorted(totals)[:3]
top3_scores = scores[:, top3_idx]
top3_totals= total[top3_idx]

# | 학생번호(idx) | 수학 | 과학 | 영어 | 총점 |
stident_nimbers = top3_idx.reshape(1,-1)
top_table = np 

AttributeError: module 'numpy' has no attribute 'sorted'